# Generated by Django 5.0.2 on 2024-02-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empl_id', models.IntegerField()),
                ('fname', models.CharField(max_length=45)),
                ('lanme', models.CharField(max_length=45)),
                ('salary', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
